/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/**/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
    fontFamily: {
      "200ExtraLight": "Cairo_200ExtraLight",
      "300Light": "Cairo_300Light",
      "400Regular": "Cairo_400Regular",
      "500Medium": "Cairo_500Medium",
      "600SemiBold": "Cairo_600SemiBold",
      "700Bold": "Cairo_700Bold",
      "800ExtraBold": "Cairo_800ExtraBold",
      "900Black": "Cairo_900Black",
    },
    colors: {
      primary: "#027AF2",
      primaryLight: "#ECF5FE",
      primaryLightSecondary: "#D5E9FC",
      orange: "#FFB029",
      orangeLight: "#FFF4E0",
      green: "#00B83D",
      greenLight: "#E4FAEF",
      pink: "#EC0066",
      pinkLight: "#FCE4ED",
      yellow: "#FFDA47",
      yellowLight: "#FEFBD7",
      red: "#FA6C68",
      purple: "#673AC2",
      purpleLight: "#EDE7F7",
      textPrimary: "#273237",
      textSecondary: "#60758B",
      background: "#FFFFFF",
      backgroundSecondary: "#F5F6F7",
      backgroundTranslucent: "#00000080",
      border: "#E1E5E8",
      unselectedNavBar: "#B8C2CB",
      selectedSegmentBg: "#FFFFFF",

      info: "#027AF2",
      warning: "#FFB029",
      success: "#00B83D",
      danger: "#F43C36",
    },
  },
  plugins: [],
};
